### ISSUE TITLE
Wrong answer

### ISSUE THREAD

**Issue by QinghuiXing** [enzoruiz/3dbinpacking#1]
hello. 
When I was testing the package I got the wrong answer in some cases.
For example. A container with shape [width, height, depth, weight] as [4, 4, 4, 10] can only contain 8 Items with shape [2, 2, 2, 1] (same dimension as above).
however, when running the code below,

'from py3dbp.main import Packer, Bin, Item
packer = Packer()

TESTBIN = Bin("Small Bin", 4, 4, 4, 10)
packer.add_bin(TESTBIN)

for i in range(10):
    packer.add_item(Item(str(i+1), 2, 2, 2, 1))

packer.pack()

for b in packer.bins:
    print(b.string())
    for i in b.items:
        print("====> ", i.string())'

I got the answer like this:

`Small Bin(4x4x4, max_weight:10)
====>  1(2x2x2, weight: 1) pos([0, 0, 0]) rt(0)
====>  2(2x2x2, weight: 1) pos([0, 0, 4]) rt(5)
====>  3(2x2x2, weight: 1) pos([0, 0, 8]) rt(5)
====>  4(2x2x2, weight: 1) pos([0, 0, 12]) rt(5)
====>  5(2x2x2, weight: 1) pos([0, 0, 16]) rt(5)
====>  6(2x2x2, weight: 1) pos([0, 0, 20]) rt(5)
====>  7(2x2x2, weight: 1) pos([0, 0, 24]) rt(5)
====>  8(2x2x2, weight: 1) pos([0, 0, 28]) rt(5)
====>  9(2x2x2, weight: 1) pos([0, 0, 32]) rt(5)
====>  10(2x2x2, weight: 1) pos([0, 0, 36]) rt(5)`

Did I use it in a wrong way?

**Comment by enzoruiz** [comment]
Hi @QinghuiXing, I recently uploaded a new version that fix the problem that you mention. I you find another problem, please let me know thanks!
