### ISSUE TITLE
Not working on a single item test case

### ISSUE THREAD

**Issue by nchaudh03** [enzoruiz/3dbinpacking#6]
packer = Packer()
packer.add_bin(Bin('Main', int(200), int(200), int(300),int(630)))
for x in range(1,101):
    packer.add_item(Item('mm' + str(x),int(65) ,int(66),int(83),int(19) ))
packer.pack(bigger_first=True)
for b in packer.bins:
    for item in b.items:
        print("====> ", item.string())

The result is 24 - In reality 27 should fit.

**Comment by jon-abbott** [comment]
I am getting a similar issue, where two items are fitting when three should actually fit... each item is identical. Here is the code I am using, based on the homepage example:
```
from py3dbp import Packer, Bin, Item

packer = Packer()

packer.add_bin(Bin('box_1', 90, 40, 30, 100))

packer.add_item(Item('item_1', 40, 30, 30, 1))
packer.add_item(Item('item_2', 40, 30, 30, 1))
packer.add_item(Item('item_3', 40, 30, 30, 1))

packer.pack()

for b in packer.bins:
    print(":::::::::::", b.string())

    print("FITTED ITEMS:")
    for item in b.items:
        print("====> ", item.string())

    print("UNFITTED ITEMS:")
    for item in b.unfitted_items:
        print("====> ", item.string())
```
Here is the output:
```
::::::::::: box_1(90x40x30, max_weight:100) vol(108000)
FITTED ITEMS:
====>  item_1(40x30x30, weight: 1) pos([0, 0, 0]) rt(0) vol(36000)
====>  item_2(40x30x30, weight: 1) pos([40, 0, 0]) rt(5) vol(36000)
UNFITTED ITEMS:
====>  item_3(40x30x30, weight: 1) pos([0, 0, 0]) rt(5) vol(36000)
```
It appears that it isn't rotating the items when placing them to use the available width of 40. If I manually rotate the items when defining them, then all three items fit as expected:
```
::::::::::: box_1(90x40x30, max_weight:100) vol(108000)
FITTED ITEMS:
====>  item_1(30x40x30, weight: 1) pos([0, 0, 0]) rt(0) vol(36000)
====>  item_2(30x40x30, weight: 1) pos([30, 0, 0]) rt(5) vol(36000)
====>  item_3(30x40x30, weight: 1) pos([60, 0, 0]) rt(5) vol(36000)
UNFITTED ITEMS:
```

**Comment by sinzii** [comment]
@nchaudh03 I managed to find a fix could solve your problem without changing RotationType.
In file [main.py:164](https://github.com/enzoruiz/3dbinpacking/blob/cd9a0dfb085c64a9599da8920a79761b493b3725/py3dbp/main.py#L164):

- The break at line 164 is meant to break out the inner loop when current item is fitted, but it not break out the outer loop at line 140.
- So we need to break out the outer loop after the inner loop like this:
```
        for axis in range(0, len(Axis.ALL)):
            for ib in bin.items:
                pivot = [0, 0, 0]
                if axis == Axis.WIDTH:
                    pivot = [
                        ib.position[0] + ib.width,
                        ib.position[1],
                        ib.position[2]
                    ]
                elif axis == Axis.HEIGHT:
                    pivot = [
                        ib.position[0],
                        ib.position[1] + ib.height,
                        ib.position[2]
                    ]
                elif axis == Axis.DEPTH:
                    pivot = [
                        ib.position[0],
                        ib.position[1],
                        ib.position[2] + ib.depth
                    ]

                if bin.put_item(item, pivot):
                    fitted = True
                    break

            if fitted:
                break
```

**Comment by enzoruiz** [comment]
Hi @nchaudh03 @jon-abbott @sinzii , i uploaded a new version (v1.1) that has the fix that @sinzii mention.
Please take a look of the new version and if there are a new problem or a new feature let us know by creating a new ticket.

Greetings!!
